### ISSUE TITLE
Allow relative path to icons

### ISSUE THREAD

**Issue by doncsugar** [Zren/plasma-applet-presentwindows#15]
Hello,

I wanted to include this in an upcoming theme. I would like for it to use an icon(s) I specify, either from the plasma theme or global theme directory. This way, everything can be automatically configured when the global theme is installed.

**Comment by Zren** [comment]
There is a `Path` KConfig type which I should be using.

* https://develop.kde.org/docs/extend/plasma/widget/configuration/#contentsconfigmainxml
* https://develop.kde.org/docs/use/configuration/kconfig_xt/

> Path: This is a string that is specially treated as a file-path. In particular paths in the home directory are prefixed with `$HOME` when being stored in the configuration file.

**Comment by doncsugar** [comment]
Thanks, looks like something I needed to be using myself.
