### ISSUE TITLE
More icon sizes

### ISSUE THREAD

**Issue by andreyorst** [Zren/plasma-applet-presentwindows#2]
With panel set for example to 24px height, 16px and 24px icons both look blurry:
![image](https://user-images.githubusercontent.com/19470159/43633679-9bbc0848-9712-11e8-81ca-f81c6f4b100d.png)
As a solution I make new icon from 24px source with 22px size (breeze use this size) but such icon looses it's dynamic color and stays black, and I don't know how to fix this.
![bitmap](https://user-images.githubusercontent.com/19470159/43634152-0ce882ca-9714-11e8-8f63-d481751f98f5.png)

I'm adding my icons here, so you may be find it easy to fix color change issue and maybe include it to plasmoid by default:
[icons.tar.gz](https://github.com/Zren/plasma-applet-presentwindows/files/2256697/icons.tar.gz)

**Comment by Zren** [comment]
When you edit via inkscape, it will change   `class="ColorScheme-Text" style="color:currentColor;"` to `style="color:#4d4d4d;"`, which means it won't follow the color scheme anymore.

Eg: https://github.com/Zren/plasma-applet-presentwindows/blob/master/package/contents/icons/presentwindows-24px.svg?short_path=c4a4c2c#L10

**Comment by Zren** [comment]
Added in v7.
