### ISSUE TITLE
suggestion: remove dimmed windows effect

### ISSUE THREAD

**Issue by savbran** [Zren/plasma-applet-presentwindows#6]
Hi, any possibility to add the function to remove windows dimming effect or at least to regulate it through a setting (GUI control in applet settings)?
I'm discussing about the dimming effect you already fixed in the youtube video:
https://www.youtube.com/watch?v=QEHC43zMIMc

Thanks in advance for your attantion and feedback.

**Comment by Zren** [comment]
I'm already subscribed to the bug report and the patch.

Someone uploaded a patch to make the dim configuration in comment #8 of that bug report. I commented on that patch.

* https://bugs.kde.org/show_bug.cgi?id=385522#c8
* https://phabricator.kde.org/D8388
