### ISSUE TITLE
Traduccion Turca

### ISSUE THREAD

**Issue by kozmotronik** [Zren/plasma-applet-presentwindows#7]
Hola amigo! Aqui te dejo una traduccion Turca por tu proyecto.
[turkish.txt](https://github.com/Zren/plasma-applet-presentwindows/files/3317004/turkish.txt)

**Comment by Zren** [comment]
That looks like translations for the PlasmaConfSaver widget. It appears the developer did not update the links in the [`translate/ReadMe.md`](https://github.com/paju1986/PlasmaConfSaver/blob/master/com.pajuelo.plasmaConfSaver/translate/ReadMe.md) to link to his widget.

Please create an issue on this project: https://github.com/paju1986/PlasmaConfSaver/issues
