### ISSUE TITLE
Parachute integration

### ISSUE THREAD

**Issue by koma111** [Zren/plasma-applet-presentwindows#9]
There is a KWin script named [Parachute](https://github.com/tcorreabr/Parachute) which adds a Gnome-like oveview. It is still in active development, but already better than Desktop Grid and Present Windows view.
Please consider adding an option for this in the settings of Present Windows Button. It would be a nice addition.

**Comment by Zren** [comment]
Use this command to confirm that "Parachute" is the shortcut id bound here: https://github.com/tcorreabr/Parachute/blob/master/contents/ui/main.qml#L97

```
qdbus org.kde.kglobalaccel /component/kwin shortcutNames | sort
qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Parachute"
```
Then modify change "ExposeAll" to "Parachute" in `~/.local/share/plasma/plasmoids/com.github.zren.presentwindows/contents/ui/Main.qml`

* https://github.com/Zren/plasma-applet-presentwindows/blob/master/package/contents/ui/Main.qml#L88

Test that the change works with:

```
plasmawindowed com.github.zren.presentwindows
```

Then restart plasma to reload the widget in the panel.

**Comment by koma111** [comment]
Thanks, I can now properly patch my Present Windows Button installation like that, this is helpful.
However, this can't be expected of everyone. When Parachute hits Beta or even Release, it would be nice to have this option in the Settings. That would save a lot of time for a lot of people.

**Comment by Zren** [comment]
Hmmm, I might be able to check if it's installed with:

```
kpackagetool5 --type=KWin/Script --list | grep Parachute
```

I didn't really want to list config options if it's not installed (as there's multiple scripts I might need to support).

**Comment by Zren** [comment]
v9 has been released with this feature.
